name: 🚀 Deploy LoanFlow API to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'LoanFlow.sln'
      - 'Dockerfile'
      - '.github/workflows/backend.yml'          # Test Run Only Backend Pipeline on push
      
env:
  IMAGE_NAME: loanflow-api
  DOCKER_REGISTRY: docker.io
  DOCKER_REPO: rycherkray
  DOCKER_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⏬ Checkout code
        uses: actions/checkout@v3

      - name: 🐳 Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: 🏗️ Build Docker image
        run: |
          docker build -t $DOCKER_REGISTRY/$DOCKER_REPO/$IMAGE_NAME:$DOCKER_TAG .

      - name: 📦 Push Docker image to Docker Hub
        run: |
          docker push $DOCKER_REGISTRY/$DOCKER_REPO/$IMAGE_NAME:$DOCKER_TAG

      - name: 🔐 Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 🔐 Deploy to Azure App Service (Container)
        uses: azure/webapps-deploy@v2
        with:
          app-name: loanflow-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}
